// Copyright (c) 2026 Konrad Zaremba
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System.Text;

namespace Betta.Docs;

/// <summary>
/// Renders the discovered components as Markdown. One file per
/// (category, sub-category) pair, plus an index.md.
/// </summary>
internal static class MarkdownEmitter
{
    public static IReadOnlyList<string> Emit(IEnumerable<DiscoveredComponent> components, string outDir)
    {
        Directory.CreateDirectory(outDir);
        var written = new List<string>();

        var groups = components
            .GroupBy(c => (c.category, c.subCategory))
            .OrderBy(g => g.Key.category, StringComparer.OrdinalIgnoreCase)
            .ThenBy(g => g.Key.subCategory, StringComparer.OrdinalIgnoreCase);

        var groupList = new List<((string Cat, string Sub) Key, List<DiscoveredComponent> Components, string File)>();

        foreach (var g in groups)
        {
            var ordered = g.OrderBy(c => c.name, StringComparer.OrdinalIgnoreCase).ToList();
            var file = $"{Sanitize(g.Key.category)}-{Sanitize(g.Key.subCategory)}.md";
            var fullPath = Path.Combine(outDir, file);

            var sb = new StringBuilder();
            sb.Append("# ").Append(g.Key.category).Append(" / ").Append(g.Key.subCategory).Append("\n\n");
            sb.Append("> ").Append(ordered.Count).Append(" component(s) in this category.\n\n");

            foreach (var c in ordered)
                AppendComponent(sb, c);

            File.WriteAllText(fullPath, sb.ToString());
            written.Add(fullPath);
            groupList.Add((g.Key, ordered, file));
        }

        // index.md
        var idx = new StringBuilder();
        idx.Append("# Betta plugin components\n\n");
        idx.Append("Auto-generated by `betta-docs` from reflected plugin DLLs. ");
        idx.Append("Each Grasshopper component listed below is produced from a method on an ");
        idx.Append("`IBettaCollection`-bearing type marked with `[GrasshopperMethod]`.\n\n");

        idx.Append("## Categories\n\n");
        foreach (var g in groupList)
        {
            idx.Append("- **").Append(g.Key.Cat).Append(" / ").Append(g.Key.Sub).Append("** — [")
               .Append(g.Components.Count).Append(" component(s)](").Append(g.File).Append(")\n");
        }

        idx.Append("\n## All components\n\n");
        idx.Append("| Component | Nickname | Category / Sub-category | Source |\n");
        idx.Append("|---|---|---|---|\n");
        foreach (var g in groupList)
        {
            foreach (var c in g.Components)
            {
                idx.Append("| [").Append(Escape(c.name)).Append("](").Append(g.File)
                   .Append("#").Append(Anchor(c.name)).Append(") ");
                idx.Append("| ").Append(Escape(c.nickName)).Append(" ");
                idx.Append("| ").Append(Escape(c.category)).Append(" / ").Append(Escape(c.subCategory)).Append(" ");
                idx.Append("| `").Append(Path.GetFileName(c.sourceDll)).Append("` |\n");
            }
        }

        var indexPath = Path.Combine(outDir, "index.md");
        File.WriteAllText(indexPath, idx.ToString());
        written.Add(indexPath);

        return written;
    }

    private static void AppendComponent(StringBuilder sb, DiscoveredComponent c)
    {
        sb.Append("## ").Append(c.name).Append("\n\n");
        sb.Append("_Nickname:_ `").Append(c.nickName).Append("`  \n");
        sb.Append("_Location:_ ").Append(c.category).Append(" / ").Append(c.subCategory).Append("  \n");
        sb.Append("_Source:_ `").Append(c.serviceType).Append('.').Append(c.methodName).Append("` in `")
          .Append(Path.GetFileName(c.sourceDll)).Append("`  \n");
        if (!string.IsNullOrEmpty(c.iconResource))
            sb.Append("_Icon:_ `").Append(c.iconResource).Append("`  \n");
        sb.Append('\n');

        sb.Append(c.description.Trim()).Append("\n\n");

        // Inputs
        sb.Append("### Inputs\n\n");
        if (c.inputs.Count == 0)
        {
            sb.Append("_No inputs._\n\n");
        }
        else
        {
            sb.Append("| Name | Nickname | Type | Access | Required | Default | Description |\n");
            sb.Append("|---|---|---|---|---|---|---|\n");
            foreach (var i in c.inputs)
            {
                sb.Append("| ").Append(Escape(i.DisplayName));
                sb.Append(" | ").Append(Escape(i.NickName));
                sb.Append(" | `").Append(Escape(i.TypeDisplay)).Append('`');
                sb.Append(" | ").Append(i.IsList ? "list" : "item");
                sb.Append(" | ").Append(i.Optional ? "no" : "yes");
                sb.Append(" | ").Append(i.HasDefault ? "`" + FormatDefault(i.DefaultValue) + "`" : "—");
                sb.Append(" | ").Append(Escape(i.Description));
                sb.Append(" |\n");
            }
            sb.Append('\n');
        }

        // Outputs
        sb.Append("### Outputs\n\n");
        if (c.outputs.Count == 0)
        {
            sb.Append("_No outputs (void method)._\n\n");
        }
        else
        {
            sb.Append("| Name | Nickname | Type | Access | Description |\n");
            sb.Append("|---|---|---|---|---|\n");
            foreach (var o in c.outputs)
            {
                sb.Append("| ").Append(Escape(o.Name));
                sb.Append(" | ").Append(Escape(o.NickName));
                sb.Append(" | `").Append(Escape(o.TypeDisplay)).Append('`');
                sb.Append(" | ").Append(o.IsList ? "list" : "item");
                sb.Append(" | ").Append(Escape(o.Description));
                sb.Append(" |\n");
            }
            sb.Append('\n');
        }

        sb.Append("---\n\n");
    }

    private static string FormatDefault(object? v) =>
        v switch
        {
            null => "null",
            string s => "\"" + s.Replace("\"", "\\\"") + "\"",
            bool b => b ? "true" : "false",
            _ => v.ToString() ?? ""
        };

    private static string Escape(string s) => string.IsNullOrEmpty(s) ? "" : s.Replace("|", "\\|").Replace("\n", " ");

    private static string Sanitize(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
            sb.Append(char.IsLetterOrDigit(ch) ? char.ToLowerInvariant(ch) : '-');
        // Collapse repeated dashes
        var collapsed = System.Text.RegularExpressions.Regex.Replace(sb.ToString(), "-+", "-").Trim('-');
        return string.IsNullOrEmpty(collapsed) ? "untitled" : collapsed;
    }

    // GitHub-style anchor: lowercase, spaces→-, drop punctuation
    private static string Anchor(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(char.ToLowerInvariant(ch));
            else if (ch == ' ' || ch == '-' || ch == '_') sb.Append('-');
        }
        return System.Text.RegularExpressions.Regex.Replace(sb.ToString(), "-+", "-").Trim('-');
    }
}
